### ISSUE TITLE
Согласовать логику проставления дедлайнов

### ISSUE THREAD

**Issue by annndruha** [profcomff/social-api#22]
@dyakovri Заполни табличку какие действия при каком случае требуются.
Сейчас работоспособное только первое. Нужно допилить остальные случаи.

| Действие \ Поле        | Taken   | Deadline       |
|-----------------|---------|----------------|
| Исп-ль назначен | Сегодня | Сегодня+неделя |
| Исп-ль изменён  |         |                |
| Исп-ль убран    |         |                |
| Добавлен второй |         |                |

**Comment by dyakovri** [comment]
Кажется, кейсы редкие и можно руками проставлять
